# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Restic Backup
version: "0.0.3"
slug: restic-backup
description: Backup your HomeAssistant instance using Restic
url: "https://github.com/jannickfahlbusch/ha-restic-backup"
arch:
  # ToDo: Reenable builds for other architectures. Restic publishes the same architectures with a different name
  #- armhf
  #- armv7
  #- aarch64
  - amd64
  #- i386
init: false
map:
  - config:ro
  - ssl:ro
  - addons:ro
  - media:ro
  - share:ro
  - backup:ro
options:
  respository:
    location: ""
    password: ""
  backup:
    host: "HomeAssistant"
    tag: "HomeAssistant"
schema:
  repository:
    location: str
    password: password
  backup:
    host: str
    tag: str

image: "ghcr.io/jannickfahlbusch/{arch}-addon-restic-backup"
